prometheus:
  url: http://ec2-35-154-253-115.ap-south-1.compute.amazonaws.com:9090/api/v1/query
  scrape_interval: 1
thresholds:
  cpu_mem_diff_percent: 10
servers:
  vm1: ec2-3-110-179-60.ap-south-1.compute.amazonaws.com:5000
  vm2: ec2-65-2-125-35.ap-south-1.compute.amazonaws.com:5000
instances:
  vm1: ec2-3-110-179-60.ap-south-1.compute.amazonaws.com:9100
  vm2: ec2-65-2-125-35.ap-south-1.compute.amazonaws.com:9100
nginx:
  config_path: /etc/nginx/conf.d/backend.conf
  access_log: /var/log/nginx/backend_access.log
  error_log: /var/log/nginx/backend_error.log
